### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriver.io#11]

**Comment by rndstr** [comment]
That would be great. As an improvement of finding the documentation for a given method, I suggest leaving the API Doc navigation sections expanded all the time. This would immensely reduce the frustration of searching for the right section of a given method (which I can never remember). I could just «Search In Page» for it.

**Comment by christian-bromann** [comment]
@rndstr I agree .. about to add a permanent searchbox on the top of the API section

**Comment by dedmau5** [comment]
awesome! I'm so looking forward to this. :+1:
