### ISSUE TITLE
document page object model with webdriverio

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriver.io#16]

**Comment by johannestroeger** [comment]
*ping*

**Comment by christian-bromann** [comment]
@johannestroeger currently working on `v3`. This version will introduce a better promise support and therefor improves the way how to construct page objects.

**Comment by christian-bromann** [comment]
Docs moved to webdriverio/webdriverio repository. There is already a [ticket](https://github.com/webdriverio/webdriverio/issues/583) created to tackle this.
