### ISSUE TITLE
Handle selenium error

### ISSUE THREAD

**Issue by cdaringe** [webdriverio/webdriver.io#22]
Hi:

Is there a way to handle the selenium error?  For example, I want to try to select an option via selectByText, specifically to confirm that it's not present.

Thanks!

**Comment by christian-bromann** [comment]
> Is there a way to handle the selenium error?

What kind of Selenium error?

The next version (v2.5.0) will allow you to query elements by content. So you could use `isExisting("option=some text")` to check if that options exists. For now I would recommend to assert the error message against `NoSuchElementException`

**Comment by cdaringe** [comment]
Thanks christian.  Cool, that will be neat in 2.5.0.  In the current scheme, I get the error, but it kills script.  Example:
```js
// select box #id has no option with visible text 'text'...
client.selectByVisibleText('#id', 'text', function(err, rs) {
    // got the err!  but script dies.  is there `proceed` or equivalent?
});
```
Are you aware of a strategy that I can use?

**Comment by christian-bromann** [comment]
@cdaringe what do you mean with the script dies? Once you pass a callback function at the end of the command you can intercept the error and the script shouldn't die at all.

**Comment by cdaringe** [comment]
you're absolutely right.  Not sure where I went astray.  Whew.  THIS IS GREAT!
