### ISSUE TITLE
Site is 404ing

### ISSUE THREAD

**Issue by vladikoff** [webdriverio/webdriver.io#24]
http://webdriver.io/ 
![image](https://cloud.githubusercontent.com/assets/128755/6717267/b14911dc-cd81-11e4-90a4-39bb5cd8809b.png)

**Comment by christian-bromann** [comment]
shoot. On it

**Comment by christian-bromann** [comment]
@vladikoff we back online again. Sorry for the outage and thanks for notifying me.

**Comment by vladikoff** [comment]
Good work guys :+1:
