### ISSUE TITLE
start-selenium is deprecated

### ISSUE THREAD

**Issue by dandv** [webdriverio/webdriver.io#33]
At http://webdriver.io/guide/getstarted/install.html, start-selenium should be `selenium-standalone start`.

Couldn't find the source file to submit a PR.

**Comment by christian-bromann** [comment]
someone made a PR webdriverio/webdriverio#745
Thanks for reporting!

**Comment by christian-bromann** [comment]
btw: all docs are within the webdriverio/webdriverio repo under `docs`
