### ISSUE TITLE
Example typo

### ISSUE THREAD

**Issue by mjurczyk** [webdriverio/webdriver.io#35]
These example typos can be deadly for someone who doesn't know JS/Selenium much:

http://webdriver.io/guide/usage/transferpromises.html

```js
.click('button=Send')
.isVisible('#status_message').then(isVisible) {
  assert.ok(isVisible, 'status message is not visible');
})
```

Missing opening parentheses before `isVisible` in `then`s callback.

**Comment by christian-bromann** [comment]
Thanks for reporting, fixed!
