### ISSUE TITLE
Change template for mobile commands in API

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriver.io#37]
- label command whether it is supported for android or for ios (see `@for` annotation)
- separate commands into commands, protocol, mobile (remove appium)

ref webdriverio/webdriverio#944

**Comment by georgecrawford** [comment]
I absolutely agree - protocol (familiar to all), commands ('sugar' layer for better API), and mobile (device-specific, with OS annotations) would be much easier to understand.

**Comment by christian-bromann** [comment]
done
