### ISSUE TITLE
Place a call to action on the website

### ISSUE THREAD

**Issue by MartinMuzatko** [webdriverio/webdriver.io#38]
It is hard to find out where to get started on the website. After reading/scanning some of the introduction and finding out:

> This is for me!

So when I was looking for a place to get started, I was confused. Only after writing this issue I scrolled up and down to notice that you have to scroll up the entire website to find the **Developer Guide**.

Thanks in advance.

**Comment by christian-bromann** [comment]
Hi @MartinMuzatko ,
Thanks for your feedback! What would you recommend?

**Comment by MartinMuzatko** [comment]
What do you think about this? @christian-bromann 

![snapshot1](https://cloud.githubusercontent.com/assets/2950505/13054547/b65a6924-d40a-11e5-8e96-6b58c665a1e3.png)

**Comment by christian-bromann** [comment]
I positioned the button right over the testimonial section:

![screen shot 2016-03-24 at 15 35 35](https://cloud.githubusercontent.com/assets/731337/14020209/78d09788-f1d6-11e5-9449-41f26948a528.png)
