### ISSUE TITLE
generating documentation for webdriverio 2.x

### ISSUE THREAD

**Issue by cancerberoSgx** [webdriverio/webdriver.io#46]
I'm having problems generating webdriverio docs for branch v2.5.0  . For latest versions instructions do work well but for 2.x webdriver.io branch they don't work. According to README.md@v2.5.0 , the command ` npm run build` should do it but is failing at "hexo generate" . It seems in latest versions of hexo it won't work. Unfortunately I'm not a hexo user and don't have much time but I really appreciate having this old version docs available. 

FYI, these are more or less the actions I'm doing: 

1) git clone https://github.com/webdriverio/webdriver.io.git
2) git checkout branchs/v2.5.0
3) perform the actions documented in the README

Could you please point me to existing compiled documentation or tell me which versions of the dependencies (hexo) should I use ? 

A suggestion for older versions it would be very useful to create a tag/branch with the compiled /public folder in the commit. It would be very very helpful for users like me that are tight to a old webdriverio version and need the docs. 

Thanks

**Comment by christian-bromann** [comment]
I would not recommend to use v2.5.0 these days anymore.
