### ISSUE TITLE
Environment version

### ISSUE THREAD

**Issue by pavelbinar** [webdriverio/webdriver.io#52]
Hi, I am unable to build project, having various issues with `node-gyp`, could you please specify exact versions for all requirements?

- node.js
- npm
- node-gyp
- hexo (`3.4.0` - there is an mismatch between hexo version specified in the `dependencies.hexo` and `hexo.verson`
- ...

Thank you!

**Comment by christian-bromann** [comment]
@pavelbinar this is the old version of the website which isn't maintained anymore. You can find the current website code in the main repo.

**Comment by pavelbinar** [comment]
@christian-bromann Thanks for quick reply!

Do you mean this one:
https://github.com/webdriverio/webdriverio ?

I do not see any instructions how to build the documentation markdowns / website.
Could be be please more specific?

**Comment by christian-bromann** [comment]
> I do not see any instructions how to build the documentation markdowns / website.

Yeah, we haven't created proper documentation around it. It uses https://docusaurus.io/ to build the website. Just go into the `website` directory and run `npm run generate`. You will find more information in the docusaurus docs.

**Comment by pavelbinar** [comment]
All right, Thanks.
